name: Bug 反馈 (Bug feedback)
description: 反馈播放失败、解析错误或软件崩溃等问题
title: "[Bug] "
labels: ["bug"]
assignees:
  - 烟雨烟中客
body:
  - type: markdown
    attributes:
      value: |
        感谢你反馈 Bug！请务必仔细阅读并填写以下信息，这将帮助我们快速定位问题。**如果问题描述不清楚，issue 将会在一天后关闭。**
  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前核对 (Pre-submission Checklist)
      options:
        - label: 我已经搜索过 [Issue Tracker](https://github.com/duanyu14/LX-MUSIC-WEB/issues)，确保没有重复的 Issue。
          required: true
        - label: 我已更新到项目的 **最新版本**，并确认问题依然存在。
          required: true
        - label: (如果是解析问题) 我已确认该音乐源在原客户端/网页端可以正常播放，排除是源本身失效的问题。
          required: false
  - type: textarea
    id: description
    attributes:
      label: 问题描述 (Description)
      description: 请清晰简洁地描述发生了什么问题。例如：在点击“网易云”源的歌曲时，提示解析失败。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤 (Steps to Reproduce)
      value: |
        1. 打开 '...'
        2. 点击 '...'
        3. 滚动到 '...'
        4. 看到错误 '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望行为 (Expected Behavior)
      description: 你认为应该发生什么？例如：应该开始播放音乐，且封面图加载正常。
    validations:
      required: true
  - type: textarea
    id: deploy_method
    attributes:
      label: 部署方式(Docker/npm/打包客户端)
      description: 填写你的部署方式
  - type: input
    id: deploy_hash
    attributes:
      label: 部署版本Hash (Deploy Hash)
      description: 可以从关于中查看 (Viewable in the About section)
      placeholder: "例如: a1b2c3d"
  - type: markdown
    attributes:
      value: |
        ### 音乐源解析问题专用 (For Music Source Parsing Issues)
        如果不是解析问题，请留空下方输入框。
  - type: input
    id: source
    attributes:
      label: 涉及的音源
      placeholder: "例如: 网易云 / QQ音乐"
  - type: input
    id: song
    attributes:
      label: 歌曲名称/链接
  - type: dropdown
    id: available_on_platform
    attributes:
      label: 是否在原平台可用
      options:
        - "是"
        - "否"
  - type: input
    id: error_msg
    attributes:
      label: 错误提示内容
  - type: input
    id: os
    attributes:
      label: 操作系统 (OS)
      placeholder: "例如: Windows 11 / macOS 13 / Android 12"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 项目版本 (Version)
      placeholder: "例如: v1.2.0"
    validations:
      required: true
  - type: input
    id: env_version
    attributes:
      label: Node版本
  - type: textarea
    id: screenshots
    attributes:
      label: 截图或录屏 (Screenshots/Video)
      description: 如有必要，请粘贴截图来展示问题。
  - type: textarea
    id: logs
    attributes:
      label: 日志输出 (Logs)
      description: 请务必提供错误日志，这是解决问题的关键！
      render: text
